name: Continuous Test Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: env.yml
      - run: |
          python -m pip install --upgrade pip
          python -m pip install pycodestyle
          pycodestyle $(git ls-files "*.py")
          pycodestyle $(git ls-files "tests/*.py")
  run_code_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: env.yml
      - run: |
          python -m pip install --upgrade pip
          python -m pip install matplotlib
          python -m pip install numpy
          conda install numpy
          conda install matplotlib
          ./run_tests.sh
